# The production config uses a few different paths to load files.
# There are also only some image dimensions specified by default.

# This production environment should be accessed via a separate virtualhost.
# An Apache example of such host configuration could be:
#
# <VirtualHost *:80>
#     DocumentRoot "<path_to_project>/public"
#     ServerName stitcher.local
#     ErrorLog "<log_path>/error.log"
#     CustomLog "<log_path>/access.log" common
#
#     <Directory "<path_to_project>/public">
#         AllowOverride All
#         Require all granted
#     </Directory>
# </VirtualHost>

# Configure the paths of several directories
directories:
    # The source directory containing
    src: ./src

    # The public directory in which the site is generated
    public: ./public

    # Cache directory used by smarty
    cache: ./cache

    # Template directory
    template: ./src/template

# Configure meta tags
meta:
    viewport: width=device-width, initial-scale=1
    chartset: utf-8
    description: High performance, static websites for PHP developers
    og:description: High performance, static websites for PHP developers

# Minify CSS and JavaScript
minify: true

# Configure engines
engines:
    # Choose the template engine. Available options: smarty, twig
    template: smarty

    # Use gd as image engine. Possible configurations: `gd` or `imagick`.
    image: gd

    # Try to use several image optimizers
    optimizer: true

caches:
    # Enable image caching while rendering
    image: false

optimizer.options:
    jpegoptim_bin: /usr/local/bin/jpegoptim
