imports:
    - /home/pageon_ssh/stitcher/config/config.yml

directories:
    public: /web/stitcher

caches:
    image: true
    cdn: true

optimizer.options:
    optipng_bin: /opt/additional_binaries/bin/optipng
    pngquant_bin: /opt/additional_binaries/bin/pngquant
    jpegoptim_bin: /opt/additional_binaries/bin/jpegoptim
