plugins:
    - Brendt\Stitcher\Plugin\PortfolioPlugin

environment: live

sitemap.url: https://www.stitcher.io

directories:
    src: ./src
    public: ./public
    cache: ./cache
    template: ./src/template

meta:
    viewport: width=device-width, initial-scale=1
    chartset: utf-8
    description: High performance, static websites for PHP developers
    og:description: High performance, static websites for PHP developers

engines:
    template: smarty
    image: gd
    optimizer: true
    minifier: true

cache:
    images: false
    cdn: false

optimizer.options:
    jpegoptim_bin: /usr/local/bin/jpegoptim

cdn:
    - img/stitcher.png
    - js/hljs.min.js
    - js/analytics.js
