imports:
    - /home/pageon_stitcher/stitcher.io/config/config.yml

environment: live

directories:
    public: /web

cache:
    images: true
    cdn: true

optimizer.options:
    optipng_bin: /opt/additional_binaries/bin/optipng
    pngquant_bin: /opt/additional_binaries/bin/pngquant
    jpegoptim_bin: /opt/additional_binaries/bin/jpegoptim

redirect.https: true
redirect.www: true
