/:
    template: home
    variables:
        content: home.md
        blog: data/blog.yml
        news: data/blog.yml
        banner: img/home_banner.jpg
    adapters:
        filter:
            blog:
                highlight: true
            news:
                news: true
        order:
            blog:
                field: date
                direction: -
            news:
                field: date
                direction: -
/blog:
    template: blog
    variables:
        posts: data/blog.yml
    adapters:
        order:
            variable: posts
            field: date
            direction: -

/blog/{id}:
    template: blog.post
    variables:
        post: data/blog.yml
    adapters:
        collection:
            variable: post
            field: id

/gallery:
    template: gallery
    variables:
        content: gallery.md
        images: gallery.yml
