/:
    template: home
    variables:
        content: data/home/home.md
        content_why: data/home/why.md
        content_installation: data/home/installation.md
        blog: data/blog/_blog.yml
        news: data/blog/_blog.yml
        banner: img/home_banner.jpg
        pageCategory: home
    adapters:
        filter:
            blog:
                highlight: true
                type: blog
            news:
                highlight: true
                type: news
        order:
            blog:
                field: date
                direction: -
            news:
                field: date
                direction: -
        limit:
            blog: 1
            news: 1

/guide/{id}:
    template: guide/detail
    variables:
        page: data/guide/_guide.yml
        pages: data/guide/_guide.yml
        pageCategory: guide
    adapters:
        guide:
            variable: pages
        collection:
            variable: page
            field: id

/guide:
    redirect: /guide/setting-up

/blog:
    template: blog/overview
    variables:
        posts: data/blog/_blog.yml
        pageCategory: blog
    adapters:
        order:
            variable: posts
            field: date
            direction: -
        pagination:
            variable: posts
            entriesPerPage: 4

/piece-of-code:
    template: blog/overview
    variables:
        title: Piece of Code
        posts: data/blog/_blog.yml
        pageCategory: blog
        intro: >
            Piece of Code is a collection of short and to the point PHP code snippets.
        meta:
            description: >
                A collection of short and to the point code snippets.
    adapters:
        filter:
            posts:
                type: piece of code
        order:
            variable: posts
            field: date
            direction: -
        pagination:
            variable: posts
            entriesPerPage: 4

/blog/{id}:
    template: blog/detail
    variables:
        post: data/blog/_blog.yml
        pageCategory: blog
    adapters:
        collection:
            variable: post
            field: id

/about:
    template: about/detail
    variables:
        content: about/about.md
        pageCategory: about
        meta: 
            title: About Stitcher and myself
            description: "A little information about myself and my favourite project: Stitcher"
