/:
    template: home
    variables:
        content: data/home/home.md
        content_why: data/home/why.md
        content_installation: data/home/installation.md
        blog: data/blog.yml
        news: data/blog.yml
        banner: img/home_banner.jpg
    adapters:
        filter:
            blog:
                highlight: true
                type: blog
            news:
                highlight: true
                type: news
        order:
            blog:
                field: date
                direction: -
            news:
                field: date
                direction: -
/blog:
    template: blog
    variables:
        posts: data/blog.yml
    adapters:
        order:
            variable: posts
            field: date
            direction: -
        pagination:
            variable: posts
            entriesPerPage: 4

/blog/{id}:
    template: blog.post
    variables:
        post: data/blog.yml
    adapters:
        collection:
            variable: post
            field: id

/gallery:
    template: gallery
    variables:
        content: gallery.md
        images: gallery.yml
